/*
 * Service manager- openapi 3.0.0
 *
 * Test task service manager
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package handler

import (
	"net/http"
)

func GetServiceStatus(c *gin.Context) {

}

func GetServices(c *gin.Context) {

}

func StartService(c *gin.Context) {

}

func TerminateService(c *gin.Context) {

}
